// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvhpwnqtprbdaikdipmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2aHB3bnF0cHJiZGFpa2RpcG16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDQzNTUsImV4cCI6MjA2OTk4MDM1NX0.CkcwIt2zptPuatzHcEk6vBa_6Hc4sr1fld5hBIedifk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});